import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../layouts/Header";
import Link from "next/link";
import { useState, useEffect } from "react";
import CharGallery from "../components/CharGallery";
import Pagination from "../components/Pagination";

export const getServerSideProps = async () => {
  const res = await fetch("https://api.disneyapi.dev/characters?page=1");
  const data = await res.json();
  return {
    props: { disney: data },
  };
};

export default function Home({ disney }) {
  const page = 1;

  return (
    <div>
      <Head>
        <title>Disney Characters</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-gray-900 text-white">
        {/* <div className="flex items-center py-6 justify-center">
          <input
            type="text"
            className="block form-control w-96 border border-slate-700 focus:text-white focus:bg-slate-800 focus:border-slate-600 focus:outline-none rounded-lg bg-slate-900 p-2"
            placeholder="Search..."
          />
          <button className="m-2 bg-slate-700 py-2 px-5 rounded-lg border border-slate-700 hover:bg-slate-800 hover:border-slate-700 focus:bg-slate-800">
            Search
          </button>
        </div> */}
        <div className="grid gap-3 mb-8 grid-cols-2 md:grid-cols-6 xl:grid-cols-8 relative mx-3 pt-5 container mx-auto">
          {disney.data.map((chars) => (
            <CharGallery key={chars._id} chars={chars} />
          ))}
        </div>
        <Pagination
          next={Number(page) + Number(1)}
          prev={Number(page) - Number(1)}
          current={page}
          total={disney.totalPages}
        />
      </div>
    </div>
  );
}
