import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../layouts/Header";

export const getStaticProps = async () => {
  const res = await fetch("https://api.disneyapi.dev/characters");
  const data = await res.json();
  return {
    props: { disney: data.data },
  };
};

export default function Home({ disney }) {
  return (
    <div>
      <Head>
        <title>Disney Characters</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="bg-gray-900 text-white">
        <div className="grid gap-3 mb-8 grid-cols-2 md:grid-cols-6 xl:grid-cols-8 relative mx-3 pt-5">
          {disney.map((chars) => (
            <div key={chars._id} className="">
              <div className="overflow-hidden h-full">
                <img
                  src={chars.imageUrl}
                  alt={chars.name}
                  className="block object-cover object-center w-full h-full rounded-lg"
                />
                <div className="flex-1">
                  <p>{chars.name}</p>
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
