import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Header from "../layouts/Header";

export const getStaticProps = async () => {
  const res = await fetch("https://api.disneyapi.dev/characters");
  const data = await res.json();
  console.log(data);
  return {
    props: { disney: data.data },
  };
};

export default function Home({ disney }) {
  return (
    <div>
      <Head>
        <title>Disney Characters</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <h1>Disney Characters</h1>
        {console.log(disney)}
        {disney.map((chars) => (
          <div key={chars._id}>
            <p>{chars.name}</p>
            <Image
              src={chars.imageUrl}
              width="50"
              height="50"
              layout="responsive"
              alt={chars.name}
            />
          </div>
        ))}
      </div>
    </div>
  );
}
